### ISSUE TITLE
Incorrect post numbering on merge post event

### ISSUE THREAD

**Issue by jordanjay29** [FriendsOfFlarum/merge-discussions#1]
Example: https://discuss.flarum.org/d/19473-need-ability-to-select-multiple-tags-when-viewing-forum/6

This was a 3 post discussion merged into a 2 post discussion (the merged discussion retained the tag and title of the 2 post version), and the post event reports only 1 post merged.

**Comment by dsevillamartin** [comment]
Issue resolved in **0.1.1**.

<img width="389" alt="image" src="https://user-images.githubusercontent.com/6401250/55115385-befe8080-50ba-11e9-9884-eea2c5493726.png">
