### ISSUE TITLE
Merging fails when attempting to merge posts into a big discussion

### ISSUE THREAD

**Issue by Yalfoosh** [FriendsOfFlarum/merge-discussions#11]
So, I'm having a problem with merging into relatively large discussions. What happens is that merging fails without a descriptive error when merging into discussions of 100 and more posts (I have yet to determine the lower bound locally). It might be only on seperated posts (unsure, have to confirm it yet), but the process I noticed the bug with is the following:

- split a post from a discussion
- try to merge a post with a large discussion (100+ posts)
- merging fails 100% of the time

I have tried to merge the post in question with a smaller discussion and it works. I have also tried to merge discussions by making it have no tags and by making it have the same tags as the discussion I'm merging with - no difference.

I'll post an update once I determine the exact details around this locally (I posted this so I don't forget it).

**Comment by dsevillamartin** [comment]
Same as #5?

**Comment by Yalfoosh** [comment]
> Same as #5?

Possible, I've reproduced it on a 29 post discussion I know there was deletion in. I might look into it, seems freaky that a global post counter system fails when there are gaps in the thread. This seems to happen even when you delete the Moderation message posts (like Merged x threads or Renamed the discussion posts), I guess?
