### ISSUE TITLE
Move comment feature

### ISSUE THREAD

**Issue by Hari-Bonda** [FriendsOfFlarum/merge-discussions#22]
as we already know sometimes we are getting errors while merging comments 

split extension is only useful to create new discussion, we can only separate single comment but If we use split to separate the comment and try to merge newly created discussion into different old discussion our merge discussions extension pops out a error.

We need "move single reply" to another discussion feature.

so we can just move the comments to different discussions without splitting or merging.

Once we move single comment from newly created discussion we can manually delete empty discussion

We request you to bring a "move comment feature" 

https://gvectors.com/wp-content/uploads/2016/03/wpDiscuz-Comment-Frontend-Moderation-move-comment.png

**Comment by Tonnie-P** [comment]
I think this can be very useful, because probably everyone had the mistake to "merge" the wrong way around, so merge the old topic in the new one instead of the new posts in the old one. (probably also because the pluging is failing randomly)

Have the plugin work this way makes it a bit more user-error proof.

**Comment by Hari-Bonda** [comment]
> I think this can be very useful, because probably everyone had the mistake to "merge" the wrong way around, so merge the old topic in the new one instead of the new posts in the old one. (probably also because the pluging is failing randomly)
> 
> Have the plugin work this way makes it a bit more user-error proof.

Hi, somone is already working on the fix check this pull request on split extension https://github.com/FriendsOfFlarum/split/pull/44
