### ISSUE TITLE
Use discussion ID instead of search

### ISSUE THREAD

**Issue by jordanjay29** [FriendsOfFlarum/merge-discussions#3]
It would be nice to be able to input the discussion ID as an advanced way of finding the discussion to merge into the current, since discussion titles can be anything (and duplicated) and search can take a while on large forums, e.g. discuss.flarum.org. 

Either as part of the existing search bar or hidden below an advanced toggle.

**Comment by dsevillamartin** [comment]
Added in 903b786b67be547e4ca41ff050d5aa8f643b2bb5.
