### ISSUE TITLE
Update recent status on merged discussions 

### ISSUE THREAD

**Issue by jordanjay29** [FriendsOfFlarum/merge-discussions#4]
Merged discussions do not have their new, more-recent replies, recognized by Flarum/discussions list. 

If discussion A is merged into discussion B, where discussion B's last reply takes place before discussion A's last reply, the discussion list will show discussion B (now merged with discussion A's posts) at the place where discussion B was last shown. It will not take on discussion A's new place, since it now contains the more recent posts that were once part of discussion A. (E.g. merging the latest discussion on the All Discussions list into one that has dropped off the front page will see the post disappear from the front page entirely instead of having the newly-merged discussion take its place).

**Comment by dsevillamartin** [comment]
Fixed in version `0.2.1`.

<img width="254" alt="image" src="https://user-images.githubusercontent.com/6401250/58052075-de95b080-7b21-11e9-9ab0-64b404382e97.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/6401250/58052082-e48b9180-7b21-11e9-9a97-d54cd4b38978.png">
